### ISSUE TITLE
nautobot-server migrate fails with nautobot_ssot_aci plugin enabled in nautobot_config.py

### ISSUE THREAD

**Issue by erwini** [nautobot/nautobot-plugin-ssot-aci#20]
### Environment

* Python version:  3.10.4
* Nautobot version:  1.3.6
* nautobot-ssot-aci version:  1.0.0

### Expected Behavior

`nautobot-server migrate` should run without errors

### Observed Behavior

`nautobot-server migrate` stops with this message:

```
nautobot@nautobot:~$ nautobot-server migrate
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, database, dcim, django_celery_beat, extras, ipam, nautobot_device_onboarding, nautobot_ssot, sessions, social_django, taggit, tenancy, users, virtualization
Running migrations:
  No migrations to apply.
Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/opt/nautobot/lib/python3.10/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
__fake__.CustomField.DoesNotExist: CustomField matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "advanced_ui" of relation "extras_customfield" violates not-null constraint
DETAIL:  Failing row contains (939d5447-515d-441d-aeec-beaa091d072c, integer, aci_pod_id, Cisco ACI Pod ID, PodID added by SSoT plugin, f, loose, null, 100, null, null, , 2022-06-27, 2022-06-27 15:03:39.480655+00, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/nautobot/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/cli.py", line 54, in main
    run_app(
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 267, in handle
    emit_post_migrate_signal(
  File "/opt/nautobot/lib/python3.10/site-packages/django/core/management/sql.py", line 48, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/opt/nautobot/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/opt/nautobot/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot/core/apps/__init__.py", line 616, in post_migrate_send_nautobot_database_ready
    nautobot_database_ready.send(sender=app_conf, app_config=app_conf, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/opt/nautobot/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/nautobot/lib/python3.10/site-packages/nautobot_ssot_aci/signals.py", line 83, in device_custom_fields
    field, _ = CustomField.objects.get_or_create(name=device_cf_dict["name"], defaults=device_cf_dict)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 576, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/base.py", line 790, in save_base
    updated = self._save_table(
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/base.py", line 933, in _do_insert
    return manager._insert(
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/opt/nautobot/lib/python3.10/site-packages/cacheops/transaction.py", line 93, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/nautobot/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "advanced_ui" of relation "extras_customfield" violates not-null constraint
DETAIL:  Failing row contains (939d5447-515d-441d-aeec-beaa091d072c, integer, aci_pod_id, Cisco ACI Pod ID, PodID added by SSoT plugin, f, loose, null, 100, null, null, , 2022-06-27, 2022-06-27 15:03:39.480655+00, null).


```

### Steps to Reproduce
1. Installation on Ubuntu 22.04
2. Installation of nautobot 1.3.6 without docker as shown in the documentation
3. Checked installation of nautobot and it works
4. added plugin nautobot-ssot (it is not clear according the documentation, if this is needed by nautobot-ssot-aci or not)
5. `nautobot-server migrate` run without errors
6. added plugin nautobot-ssot-aci according documentation
7. `nautobot-server migrate` run/stops with errors

**Comment by dnewood** [comment]
@erwini I'm able to replicate this as well and it seems like a `pip` dependency resolution issue that I want to look more into. Could you do me a favor and double check to see if `nautobot-server --version` is still actually returning `1.3.6`? 

If it doesn't return `1.3.6` then you should be able to run `pip3 install nautobot==1.3.6` to make pip go back to the proper version. I was able to get it to work by doing this in our lab but its not a very good solution so I'll look more into this

Update:
This looks to be related to the PyYAML and Jinja2 pinning within pyproject.toml. I'll get a PR submitted to get this fixed

**Comment by erwini** [comment]
@chadell I checked with `nautobot-server --version` and it comes back with 1.2.11. But i was pretty sure, the gui before installing the plugins shows `1.3.6`. I reverted to the VM snapshot before installing the plugins and now i get `1.3.6` with the gui and `nautobot-server --version`. So something is reverting to 1.2.11 !?

**Comment by erwini** [comment]
Tested to do `pip3 i nstall nautobot==1.3.6`.

Result:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nautobot-ssot-aci 1.0.0 requires Jinja2<3, but you have jinja2 3.0.3 which is incompatible.
nautobot-ssot-aci 1.0.0 requires PyYAML<6.0.0,>=5.4.1, but you have pyyaml 6.0 which is incompatible.
```
Maybe it helps ...

**Comment by dnewood** [comment]
@erwini yeah that confirms you are seeing the same issue that I am. I am prepping a PR to address this and will get it submitted for review.

**Comment by erwini** [comment]
Short of topic question: how to set the enviroment varibales for the apic, so they can be seen in the drop down menu in gui to select the apic? No hint in the documentation.

**Comment by chadell** [comment]
> Short of topic question: how to set the enviroment varibales for the apic, so they can be seen in the drop down menu in gui to select the apic? No hint in the documentation.

Hi @erwini , here you have it: https://github.com/nautobot/nautobot-plugin-ssot-aci/blob/develop/docs/install_configure.md#per-apic-settings

**Comment by erwini** [comment]
> > Short of topic question: how to set the enviroment varibales for the apic, so they can be seen in the drop down menu in gui to select the apic? No hint in the documentation.
> 
> Hi @erwini , here you have it: https://github.com/nautobot/nautobot-plugin-ssot-aci/blob/develop/docs/install_configure.md#per-apic-settings

I have seen this, but where do i set this enviroments ? In a file or somewhere in the GUI? If in file, in which file ? How is this file called/executed with which user? A small example where helpful. It is not a docker installation.

**Comment by chadell** [comment]
This environment variables are the shell one. For instance, in Linux you simply `export` them. 
If you are using a service loader, such as `systemd`, follow the rules. `systemd` recommended [way](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines) is adding them in the a `.conf` file:

```
[Service]
Environment="MYENV=whatever"
```

**Comment by chadell** [comment]
@erwini could we close this issue?
